$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

source = ~/.config/hypr/conf/monitor.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/decorations.conf
source = ~/.config/hypr/conf/workspaces.conf
source = ~/.config/hypr/conf/rules.conf


general {
    gaps_out = 4, 18, 18, 18
}


# Eww music popup — liquid glass

