animations {
    enabled = yes

    # -------- Curves --------
    bezier = overshot, 0.20, 1, 0.30, 1
    bezier = smoothOut, 0.22, 1, 0.36, 1
    bezier = smoothInOut, 0.65, 0, 0.35, 1
    bezier = fast, 0.4, 0, 0.2, 1

    # -------- Windows --------
    animation = windows, 1, 6, overshot, popin 88%
    animation = windowsOut, 1, 5, smoothInOut, popin 86%
    animation = windowsMove, 1, 5, smoothOut, slide

    # -------- Fade --------
    animation = fade, 1, 6, smoothOut
    animation = fadeShadow, 1, 8, smoothOut
    animation = fadeDim, 1, 8, smoothOut

    # -------- Border --------
    animation = border, 1, 8, smoothOut
    animation = borderangle, 1, 12, smoothOut

    # -------- Layers --------
    animation = layers, 1, 5, smoothOut, slide

    # -------- Workspaces --------
    animation = workspaces, 1, 5, smoothOut, slidefade 10%
    animation = specialWorkspace, 1, 8, overshot, slidefadevert 20%
}
