# Waybar
exec-once = waybar

# Notifications
exec-once = swaync

# Bluetooth
exec-once = blueman-applet

# Wi-Fi
exec-once = nm-applet --indicator

# Live Wallpaper
exec-once = mpvpaper -o "no-audio loop hwdec=auto" "*" ~/Downloads/1405430.mp4

# Idle daemon
exec-once = hypridle

# Volume OSD
exec-once = swayosd-server
