# Waybar
exec-once = waybar

# Notifications
exec-once = swaync

# Bluetooth
exec-once = blueman-applet

# Wi-Fi
exec-once = nm-applet --indicator

# Live Wallpaper
exec-once = waypaper --restore

# Idle daemon
exec-once = hypridle

# Volume OSD
exec-once = swayosd-server

# Clipboard History
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
